### PR TITLE
Support for full rendering API

### PR DESCRIPTION
**Pull request by wezm**
This PR adds support for the full rendering API.

I fully admit I changed a lot of stuff, including upgrading all dependencies first. If you don't want all the changes then the approach of including the functions into two different modules should be easily reproducible in isolation.

### CODE REVIEW

**Comment by rhysforyou** [comment]
This is fantastic, thank you! I'll take some time to code review it tonight.

**Comment by rhysforyou** [comment]
I've merged these changes with a few tweaks (mainly running `refmt` and removing some comments). I'll get a release out shortly.

**Comment by rhysforyou** [comment]
Alright this has been released as `0.5.0`

**Comment by wezm** [comment]
Excellent, thank you.

**Pull request merged**
