### PR TITLE
Support for ES6 modules

### PR DESCRIPTION
**Pull request by erykpiast**
It resolves https://github.com/rhysforyou/bs-enzyme/issues/14 but potentially breaks projects compiled directly to ES5.

### CODE REVIEW

**Comment by erykpiast** [comment]
@rhysforyou Is there any chance to merge this?

**Comment by erykpiast** [comment]
@rhysforyou do you need help with the maintenance of governance of the project? It would be a pleasure for me to help with that.

**Comment by rhysforyou** [comment]
@erykpiast more than happy to have others help out. I haven't been able to give much time to this project, and haven't been using Reason in any recent projects, so I'm a little rusty. If there are those in the community who want to help out, I'd greatly appreciate it.

**Comment by erykpiast** [comment]
@rhysforyou great! I'll try to go through the backlog over the weekend and at least think about unresolved issues.

**Pull request merged**
